# Generated by Django 3.2 on 2021-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_upload',
            name='filetype',
            field=models.CharField(max_length=200),
        ),
    ]
