# Generated by Django 3.2 on 2021-04-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_alter_files_upload_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.user_profile', unique=True),
        ),
    ]
