# Generated by Django 3.2 on 2021-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='approvestatus',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
