# Generated by Django 3.2 on 2021-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_notifications_approvestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='display_picture',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
